image: maven:3.3.9-jdk-8

before_script:
  - apt-get update
  - apt-get install -y openjfx

build:
  script:
    - mvn clean install -B
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
